name: Unit test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  bats:
    name: Run unit test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup BATS
        uses: mig4/setup-bats@v1

      - name: Run bats
        run: bats test
